apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-migrate
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: taskhub.azurecr.io/taskhub:v4
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ManagedIdentityClientId
              value: "<your-managed-identity-client-id>"
          command: ["dotnet", "TaskHub.dll", "--migrate-only"]
